MyStay/MyStayMVC/MyStayMVC/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyStayMVC.Models
{
    public class Booking
    {
        public Booking()
        {
            lstBooking = new List<Booking>();
        }
        public int ID { get; set; }
        public int ParentHotelID { get; set; }
        public int ParentRoomID { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string HotelName { get; set; }
        public string RoomNumber { get; set; }
        public List<Booking> lstBooking { get; set; }
        public string Selectedvalue { get; set; }
        public string PaidStatus { get; set; }
    }
}

MyStay/MyStayMVC/MyStayMVC/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyStayMVC.Models;
using MyStayMVC.Utility;

namespace MyStayMVC.Controllers
{
    public class BookingController : Controller
    {
        public IActionResult BookingDetails()
        {
            Booking booking = new Booking();
            booking.lstBooking = GetAllBookingDetails();
            GetDropDownList();
            return View(booking);
        }

        public IActionResult AddBooking()
        {
            GetDropDownList();
           return View();
        }

        private void GetDropDownList()
        {
            ViewBag.lstHotelInfo = new SelectList(new HotelInfoController().GetAllHotelInfo().ToList(),"ID","Name");
            ViewBag.lstRooms = new SelectList(new RoomController().GetAllRoomDetails().ToList().ToList(), "ID", "RoomNumber");
        }

        [HttpPost]
        public ActionResult SubmitBookingDetails(Booking booking)
        {
            int response = HelperClass.httpPostAysnc<Booking>(booking, "api/Booking/PostBookingDetails").Result;
            ModelState.Clear();
            return RedirectToAction("BookingDetails");
        }
        public List<Booking> GetAllBookingDetails()
        {
            return HelperClass.httpGetTAsync<List<Booking>>("api/Booking/GetAllBookingDetails").Result;
        }
        [HttpPost]
        public ActionResult BookingDetails(Booking booking)
        {
            List<Booking> lstbooking = GetAllBookingDetails();
            
            booking.lstBooking = lstbooking.Where(x => x.ParentHotelID.Equals(booking.ParentHotelID) ||
                                             x.ParentRoomID.Equals(booking.ParentRoomID) ||
                                             (x.StartDate >= booking.StartDate && x.EndDate <= (booking.EndDate==null?DateTime.Now.Date:booking.EndDate))).ToList();
            GetDropDownList();
            return View("BookingDetails", booking);
        }

    }
}

MyStay/MyStayMVC/MyStayMVC/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyStayMVC.Models;
using MyStayMVC.Utility;

namespace MyStayMVC.Controllers
{
    public class RoomController : Controller
    {
        [Route("Room/RoomDetails")]
        public IActionResult RoomDetails()
        {
            RoomDetails roomDetails = new RoomDetails();
            roomDetails.lstRoomDetails = GetAllRoomDetails().OrderByDescending(x => x.ID).ToList();
            return View(roomDetails);
        }
        [Route("Room/RoomDetails/{id}")]
        public IActionResult RoomDetails(int ID,string HotelName)
        {
            ModelState.Clear();
            RoomDetails roomDetails = new RoomDetails();
            roomDetails.HotelName = HotelName;
            roomDetails.ParentHotelID = ID;
            roomDetails.lstRoomDetails = GetAllRoomDetails().Where(x=>x.ParentHotelID.Equals(ID)).OrderByDescending(x => x.ID).ToList();
            return View("RoomDetails", roomDetails);
        }
        public IActionResult GetRoomDetails(string ID,string HotelName)
        {
            return RedirectToAction("RoomDetails", new { ID = Convert.ToInt32(ID), HotelName = HotelName });
        }
        [HttpPost]
        public ActionResult SubmitRoomDetails(RoomDetails roomDetails)
        {
            int response = HelperClass.httpPostAysnc<RoomDetails>(roomDetails, "api/Room/PostRoomDetails").Result;
            ModelState.Clear();
            return RedirectToAction("RoomDetails", new { ID=roomDetails.ParentHotelID, HotelName=roomDetails.HotelName });
        }

        public List<RoomDetails> GetAllRoomDetails()
        {
            return HelperClass.httpGetTAsync<List<RoomDetails>>("api/Room/GetAllRoomDetails").Result;
        }
    }
}

MyStay/MyStayMVC/MyStayMVC/Views/Booking/AddBooking.cshtml
@model MyStayMVC.Models.Booking
@{
    ViewData["Title"] = "BookingDetails";
    ViewBag.Active = "Booking";
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#StartDate").datepicker();
        $("#EndDate").datepicker();
    });
</script>
<div class="widget box">
    <div class="widget-header">
        <h4><i class="icon-reorder"></i> Add Booking Details</h4>
    </div>
    <div class="widget-content">
        @using (Html.BeginForm("SubmitBookingDetails", "Booking", FormMethod.Post, new { @id = "SubmitBookingDetails" }))
        {
            <div class="row">
                <label class="col-md-2 control-label">Hotel Name <span class="required">*</span></label>
                <div class="form-group  col-md-3">
                    @Html.DropDownListFor(model => model.ParentHotelID,
                                            (IEnumerable<SelectListItem>)(ViewBag.lstHotelInfo), "--Select Hotel --",
                                            new {@class = "form-control" })
                </div>
            </div>
            <div class="row">
                <label class="col-md-2 control-label">Room Number <span class="required">*</span></label>
                <div class="form-group col-md-3">
                    @Html.DropDownListFor(model => model.ParentRoomID,
                                       (IEnumerable<SelectListItem>)(ViewBag.lstRooms), "-- Select Room Number --",
                                        new {@class = "form-control"})
                </div>
            </div>
            <div class="row">
                <label class="col-md-2 control-label">Start Date<span class="required">*</span></label>
                <div class="form-group  col-md-2">
                    @Html.TextBoxFor(model => model.StartDate, new { @autocomplete = "off", @class = "form-control", @placeholder = "Select Start Date" })
                </div>
            </div>
            <div class="row">
                <label class="col-md-2 control-label">End Date<span class="required">*</span></label>
                <div class="form-group  col-md-2">
                    @Html.TextBoxFor(model => model.EndDate, new { @autocomplete = "off", @class = "form-control", @placeholder = "Select End Date" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-1a">
                    <button type="submit" class="btn btncusSave btn-block btn-flat">Save</button>
                </div>
                <div class="form-group col-md-1a" style="margin-left:-10px;">
                    <button type="button" class="btn btncusCancel btn-block btn-flat" onclick="location.href='@Url.Action("BookingDetails","Booking")'">Cancel</button>
                </div>
            </div>
        }
    </div>

</div>
<!-- /Validation Example 1 -->

MyStay/MyStayMVC/MyStayMVC/Views/Booking/BookingDetails.cshtml
@model MyStayMVC.Models.Booking
@{
    ViewData["Title"] = "BookingDetails";
    ViewBag.Active = "Booking";
}



<script type="text/javascript">
    $(document).ready(function () {
        $("#StartDate").datepicker();
        $("#EndDate").datepicker();
    });
</script>
<div class="widget box">
    <div class="widget-header">
        <h4><i class="icon-reorder"></i> Booking Details</h4>
        <div class="col-md-1 " style="float:right;">
            <button type="button" class="btn btncusCancel btn-block btn-flat" onclick="location.href='@Url.Action("AddBooking","Booking")'">Add</button>
        </div>
    </div>
    <div class="widget-content">
        @using (Html.BeginForm("BookingDetails", "Booking", FormMethod.Post, new { @id = "SubmitBookingDetails" }))
        {
            <div class="row">
                <div class="form-group  col-md-3">

                    @Html.DropDownListFor(model => model.ParentHotelID,
                                           (IEnumerable<SelectListItem>)(ViewBag.lstHotelInfo), "--Select Hotel --",
                                            new {@class = "form-control", data_val = false })
                </div>
                <div class="form-group col-md-3">
                    @Html.DropDownListFor(model => model.ParentRoomID,
                                         (IEnumerable<SelectListItem>)(ViewBag.lstRooms), "-- Select Room Number --",
                                        new {@class = "form-control", data_val = false })
                </div>
                <div class="form-group  col-md-2">
                    @Html.TextBoxFor(model => model.StartDate, new { @autocomplete = "off", @class = "form-control", @placeholder = "Select Start Date" })
                </div>
                <div class="form-group  col-md-2">
                    @Html.TextBoxFor(model => model.EndDate, new { @autocomplete = "off", @class = "form-control", @placeholder = "Select End Date" })
                </div>
                <div class="form-group col-md-1a">
                    <button type="submit" class="btn btncusCancel btn-block btn-flat">Search</button>
                </div>
            </div>
        }
        @Html.Partial("~/Views/Booking/_BookingDetailsList.cshtml")
    </div>

</div>
<!-- /Validation Example 1 -->

MyStay/MyStayMVC/MyStayMVC/Views/Booking/_BookingDetailsList.cshtml
@using MyStayMVC.Utility;

<script type="text/javascript">
    $(document).ready(function () {
        //triggered when modal is about to be shown
        $('#myModal').on('show.bs.modal', function (e) {
            debugger;
            ID = $(e.relatedTarget).data('id');
            $('#hdnBookingID').val(ID);
        });
        $('#btnPay').click(function () {
            var ID = $('#hdnBookingID').val();
            debugger;
            $.ajax({
                cache: false,
                type: 'POST',
                url: '/Payment/PaymentDetails',
                data: 'ID=' + ID,
                success: function (data) {
                    window.location.href = "/Booking/BookingDetails";
                }
            });
        });
    });
</script>

<div id="divBookingInfoDetails">
    @if (Model.lstBooking.Count > 0)
    {
        <table class="table table-hover table-striped table-responsive">
            <thead font-weight:bold;" style="background-color:#d3d3d36e;">
                <tr>
                    <th>Hotel Name</th>
                    <th>Room Number</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Payment</th>
                </tr>
            </thead>
            @foreach (Booking oBooking in Model.lstBooking)
            {
                <tr style="line-height:14px;">
                    <td>@oBooking.HotelName</td>
                    <td>@oBooking.RoomNumber</td>
                    <td>@String.Format("{0:dd MMM yyyy}", oBooking.StartDate)</td>
                    <td>@String.Format("{0:dd MMM yyyy}", oBooking.EndDate)</td>
                    <td>
                        @*href="@Url.Action("Payment", "Room", new { ID = oBooking.ID.ToString() })"*@
                        @if (oBooking.PaidStatus.Equals(Constants.PaymentStatus_Paid))
                        {
                        <p>@Constants.PaymentStatus_Paid</p>
                                }
                        else
                        {
                            <button type="button" data-toggle="modal" data-target="#myModal" data-id="@oBooking.ID">
                                Payment
                            </button>
                        }

                    </td>

                </tr>
            }
        </table>
    }
    else
    {
        <div>
            No Bookings found
        </div>
    }
</div>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <input type="hidden" id="hdnBookingID" />
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Payment</h4>
            </div>
            <div class="modal-body">
                <p>Do you want to make the Payment?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="padding-left: 20px;" id="btnPay">Pay</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>